kind: pipeline
name: default

workspace:
   base: /go
   path: src/github.com/fanux/store/

steps:
- name: build-backend
  image: fanux/store-back:dev
  commands:
     - cd store && pwd && ls && go build -o store-back 

- name: publish-back
  image: plugins/docker
  settings:
    repo: fanux/store-back
    tags: ${DRONE_TAG=latest}
    username: fanux
    dockerfile: Dockerfile-back
    password:
      from_secret: docker-hub-pass

- name: deploy-back
  image: lachlanevenson/k8s-kubectl
  commands:
    - mkdir ~/.kube
    - cp deploy/config ~/.kube/config
    - kubectl delete -f deploy/store-back.yaml || true
    - sleep 15
    - kubectl create -f deploy/store-back.yaml || true

- name: build-font
  image: fanux/vue:latest
  commands:
     - cd font && npm install vue && npm install vue-router && npm install iview --save && npm install vue-resource  && npm install vue-router
     - npm run build

- name: publish-font
  image: plugins/docker
  settings:
    repo: fanux/store-font
    tags: ${DRONE_TAG=latest}
    username: fanux
    dockerfile: Dockerfile-font
    password:
      from_secret: docker-hub-pass

- name: deploy-font
  image: lachlanevenson/k8s-kubectl
  commands:
    - mkdir ~/.kube
    - cp deploy/config ~/.kube/config
    - kubectl delete -f deploy/store-font.yaml || true
    - sleep 15
    - kubectl create -f deploy/store-font.yaml || true

