kind: pipeline
name: default
workspace:
   base: /go
   path: src/github.com/sealyun/
    

steps:
    #- name: build-font
    #  image: fanux/store-font:dev
    #  commands:
    #     - cd font
    #     - npm build
    #
    #- name: publish-font
    #  image: plugins/docker
    #  settings:
    #    repo: fanux/store-font
    #    tags: ${DRONE_TAG=latest}
    #    username: fanux
    #    password:
    #      from_secret: docker-hub-pass
- name: build-backend
  image: fanux/store-back:dev
  commands:
     - cd store && pwd && ls && go build -o store-back 

- name: publish-back
  image: plugins/docker
  settings:
    repo: fanux/store-back
    tags: ${DRONE_TAG=latest}
    username: fanux
    dockerfile: Dockerfile-back
    password:
      from_secret: docker-hub-pass
