kind: pipeline
name: default

workspace:
   base: /go
   path: src/github.com/sealyun/store/

steps:
- name: build-backend
  image: fanux/store-back:dev
  commands:
     - cd store && pwd && ls && go build -o store-back 

- name: publish-back
  image: plugins/docker
  settings:
    repo: fanux/store-back
    tags: ${DRONE_TAG=latest}
    username: fanux
    dockerfile: Dockerfile-back
    password:
      from_secret: docker-hub-pass

- name: deploy-back
  image: lachlanevenson/k8s-kubectl
  commands:
    - mkdir ~/.kube
    - cp deploy/config ~/.kube/config
    - kubectl delete -f deploy/store-back.yaml || true
    - kubectl create -f deploy/store-back.yaml || true

