apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-back
  labels:
    app: store-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-back
  template:
    metadata:
      labels:
        app: store-back
    spec:
      containers:
      - name: store-back
        image: fanux/store-back:latest
        imagePullPolicy: Always
      hostNetwork: true
