apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-back
  labels:
    app: store-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-back
  template:
    metadata:
      labels:
        app: store-back
    spec:
      volumes:
      - hostPath:
          path: /data
          type: DirectoryOrCreate
        name: data
      containers:
      - name: store-back
        image: fanux/store-back:latest
        volumeMounts:
         - mountPath: /data
           name: data
        command:
            - ./store-back
            - serve
            - -d
            - "store.lameleg.com"
            - -p
            - "8080"
        imagePullPolicy: Always
      hostNetwork: true
