apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-font
  labels:
    app: store-font
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-font
  template:
    metadata:
      labels:
        app: store-font
    spec:
      containers:
      - name: store-font
        image: fanux/store-font:latest
        imagePullPolicy: Always
      hostNetwork: true
